#!/usr/bin/env python3
"""Balance beam: walk the duck along a narrow raised beam without stepping off.

The pretrained walking policy does the walking. This script does the steering:
every control tick it reads the trunk's lateral offset from the beam's
centreline and its heading, and feeds a yaw-rate command back into the
policy's twist command. The forward command stays constant. The policy cannot
strafe (a lateral command produces zero lateral motion, see HANDOFF.md), so
the only way back to the centreline is to aim at it: P on lateral error sets
a desired heading, P on heading error sets the yaw rate.

A step-off is a foot touching the FLOOR geom (not the beam), any other part of
the robot touching floor or beam, or the trunk dropping to fall height above
the beam. The run reports how far it walked, when it stepped off, which foot
went over which edge, and the largest lateral error it saw.

    uv run python -m microduck_lab.tasks.walking.balance_beam --width 0.12
    uv run python -m microduck_lab.tasks.walking.balance_beam --sweep 0.30 0.20 0.15 0.12 0.10 0.08
    MUJOCO_GL=egl uv run --with imageio --with imageio-ffmpeg \\
        src/microduck_lab/tasks/walking/balance_beam.py --width 0.12 --video videos/balance_beam/beam_w012.mp4

--video needs a GPU (EGL); the task itself runs anywhere.
"""

import argparse
import contextlib
import io
import os
import re
import sys

import numpy as np


import mujoco  # noqa: E402
from microduck_lab.sim import duck_sim
from microduck_lab.sim.duck_sim import CONTROL_DT, DECIMATION  # noqa: E402

ROBOT_DIR = os.path.join(duck_sim.REPO, "src", "mjlab_microduck", "robot", "microduck")
TEMPLATE = os.path.join(ROBOT_DIR, "scene_beam.xml")
WALKING_ONNX = os.path.join(os.path.dirname(duck_sim.REPO), "microduck", "policies", "alpha_walking.onnx")

# The beam starts this far behind the duck, so the start is not on an edge.
BEAM_BEHIND = 0.30
# The finish line sits this far before the far end. The duck stops there; the
# last 100 mm (about two foot lengths) is never walked, so a run can succeed
# without the feet reaching the end face.
FINISH_MARGIN = 0.10
# Stand still this long before walking, so the drop onto the beam has settled.
SETTLE_S = 1.0
# Trunk height above the support surface in a stand is ~0.12 m; below this
# (above the beam top) the duck is down. Same number as duck_sim.FALL_HEIGHT.
FALL_HEIGHT = duck_sim.FALL_HEIGHT
# Keep simulating this long after a step-off so a video shows the fall.
AFTER_FAIL_S = 1.0
# The trunk walks 0.11-0.12 m above the surface. Lateral error and foot
# placement are only counted while it is at least this high above the beam
# top, so a fall in progress does not inflate them.
UPRIGHT = 0.105


RUNWAY_WIDTH = 0.30


def write_scene(width, length, height, runway=0.0):
    """Write scene_beam_w<W>.xml next to the template, beam sized as asked.

    The template's beam line is replaced; everything else (floor, lights,
    robot include) is copied through. Rewritten on every run, so a stale file
    with the same width but a different length or height cannot survive.

    `runway` > 0 adds a 0.30 m wide platform of that length at the start, at
    beam height, so the duck can get its gait going before the narrow part.
    It is off by default: the task as set starts on the narrow beam.
    """
    with open(TEMPLATE) as f:
        src = f.read()
    cx = -BEAM_BEHIND + length / 2.0
    geom = (f'<geom name="beam" type="box" size="{length / 2:.4f} {width / 2:.4f} {height / 2:.4f}" '
            f'pos="{cx:.4f} 0 {height / 2:.4f}" rgba="0.85 0.65 0.35 1" />')
    if runway > 0:
        geom += (f'\n        <geom name="runway" type="box" size="{runway / 2:.4f} {RUNWAY_WIDTH / 2:.4f} {height / 2:.4f}" '
                 f'pos="{-BEAM_BEHIND + runway / 2:.4f} 0 {height / 2:.4f}" rgba="0.75 0.55 0.30 1" />')
    out, n = re.subn(r'<geom name="beam"[^>]*/>', geom, src)
    if n != 1:
        sys.exit(f"{TEMPLATE}: expected exactly one beam geom, found {n}")
    out = out.replace("<mujoco model=\"scene_beam\">",
                      f"<mujoco model=\"scene_beam_w{width:.3f}\">\n"
                      f"    <!-- GENERATED by src/microduck_lab/tasks/walking/balance_beam.py from scene_beam.xml; do not edit. -->", 1)
    path = os.path.join(ROBOT_DIR, f"scene_beam_w{width:.3f}.xml")
    # Written whole-or-not: a sweep run in parallel reloads the same file.
    tmp = f"{path}.{os.getpid()}.tmp"
    with open(tmp, "w") as f:
        f.write(out)
    os.replace(tmp, path)
    return path


def ground(model, data, adr, clearance=0.002, lo=0.05, hi=0.40):
    """Lowest contact-free trunk height, plus a small clearance.

    Binary search on the trunk z with the joints frozen (the harness.py
    `_ground` pattern). The duck then drops `clearance` onto the beam rather
    than the 8 mm it drops onto the floor from duck_sim's 0.125 m start.
    """
    for _ in range(40):
        mid = 0.5 * (lo + hi)
        data.qpos[adr + 2] = mid
        mujoco.mj_forward(model, data)
        if data.ncon > 0:
            lo = mid
        else:
            hi = mid
    data.qpos[adr + 2] = hi + clearance
    mujoco.mj_forward(model, data)
    return hi


def foot_extent(model, data, name):
    """World-frame axis-aligned bounds of a sole mesh, as (min_xyz, max_xyz)."""
    g = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, name)
    m = model.geom_dataid[g]
    va, vn = model.mesh_vertadr[m], model.mesh_vertnum[m]
    v = model.mesh_vert[va:va + vn]
    w = v @ data.geom_xmat[g].reshape(3, 3).T + data.geom_xpos[g]
    return w.min(axis=0), w.max(axis=0)


def run(width, length, height, speed, seconds, k_lat, k_yaw, max_aim, max_turn,
        turn_bias=0.0, steer_delay=0.0, runway=0.0, y0=0.0, walking=WALKING_ONNX, video=None,
        fps=30, cam_distance=0.9, azimuths=(130.0,), log_every=2.0, verbose=True):
    """One beam run. Returns a dict of measured outcomes."""
    say = print if verbose else (lambda *a, **k: None)
    quiet = contextlib.redirect_stdout(io.StringIO())

    xml = write_scene(width, length, height, runway)
    model, data = duck_sim.load_scene(xml)
    with quiet:
        policy, adr = duck_sim.make_policy(model, data, walking_onnx_path=walking)

    gid = lambda n: mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, n)
    sid = lambda n: mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, n)
    floor, beam = gid("floor"), gid("beam")
    runway_g = gid("runway")  # -1 when there is none
    surfaces = {beam, runway_g}
    feet = {gid("left_foot_collision"): "left", gid("right_foot_collision"): "right"}
    foot_site = {"left": sid("left_foot"), "right": sid("right_foot")}
    trunk = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "trunk_base")

    # Start on the beam: trunk over the centreline (plus any asked-for offset),
    # heading +x, resting on the beam top.
    data.qpos[adr + 0] = 0.0
    data.qpos[adr + 1] = y0
    data.qpos[adr + 3:adr + 7] = [1, 0, 0, 0]
    z_rest = ground(model, data, adr)
    data.qvel[:] = 0.0
    mujoco.mj_forward(model, data)

    lmin, lmax = foot_extent(model, data, "left_foot_collision")
    rmin, rmax = foot_extent(model, data, "right_foot_collision")
    stance = float(data.site_xpos[foot_site["left"]][1] - data.site_xpos[foot_site["right"]][1])
    say(f"beam:    {length:.2f} m long, {width * 1000:.0f} mm wide, {height * 1000:.0f} mm high; "
        f"edges at y = +/-{width * 500:.1f} mm; finish line at x = {length - BEAM_BEHIND - FINISH_MARGIN:+.2f} m")
    say(f"stance:  foot centres {stance * 1000:.1f} mm apart; soles span y = "
        f"[{rmin[1] * 1000:+.1f}, {rmax[1] * 1000:+.1f}] and [{lmin[1] * 1000:+.1f}, {lmax[1] * 1000:+.1f}] mm "
        f"({(lmax[1] - lmin[1]) * 1000:.1f} mm wide, {(lmax[0] - lmin[0]) * 1000:.0f} mm long); "
        f"trunk rests at z = {z_rest:.4f} m ({(z_rest - height) * 1000:.1f} mm above the beam top)")
    half_outer = 0.5 * (lmax[1] - rmin[1])  # outer sole edge to outer sole edge, halved
    overhang = max(0.0, half_outer - width / 2)
    say(f"         each foot overhangs its edge by {overhang * 1000:.1f} mm in the home stance, centred"
        + ("; foot CENTRES are outside the beam" if stance / 2 > width / 2 else ""))
    if runway > 0:
        say(f"runway:  {RUNWAY_WIDTH * 1000:.0f} mm wide for the first {runway:.2f} m; "
            f"the narrow beam starts at x = {runway - BEAM_BEHIND:+.2f} m")

    recs = []
    if video:
        base, ext = os.path.splitext(video)
        for az in azimuths:
            path = video if len(azimuths) == 1 else f"{base}_az{int(round(az))}{ext}"
            recs.append((path, duck_sim.Recorder(model, fps=fps, distance=cam_distance, azimuth=az)))

    finish_x = length - BEAM_BEHIND - FINISH_MARGIN
    steps = int(round(seconds / CONTROL_DT))
    res = {
        "width": width, "height": height, "length": length, "speed": speed,
        "y0": y0, "stance": stance, "overhang": overhang,
        "distance": 0.0, "walk_time": 0.0, "max_lat": 0.0, "max_yaw": 0.0,
        "max_foot_out": 0.0, "min_z": float("inf"), "success": False, "fail_t": None, "fail": None,
        "upright_lat": 0.0, "upright_yaw": 0.0, "upright_t": None,
    }
    phase = "settle"
    walk_t0 = None
    x0 = None
    stop_at = None
    turn = 0.0
    last_log = -1.0

    with quiet:
        policy.set_vel_cmd(0.0, 0.0, 0.0)

    for i in range(steps):
        t = i * CONTROL_DT
        x, y = float(data.qpos[adr]), float(data.qpos[adr + 1])
        yaw = duck_sim.trunk_yaw(data, adr)

        if phase == "settle" and t >= SETTLE_S:
            phase = "walk"
            walk_t0, x0 = t, x
            say(f"t={t:4.1f}s  walking at {speed:.2f} m/s from x={x:+.3f} y={y * 1000:+.1f} mm")

        if phase == "walk":
            # Aim at the centreline: a lateral offset to the left (+y) asks
            # for a heading to the right (-yaw), and the yaw rate chases it.
            aim = float(np.clip(-k_lat * y, -max_aim, max_aim))
            turn = float(np.clip(k_yaw * (aim - yaw) + turn_bias, -max_turn, max_turn))
            if t - walk_t0 < steer_delay:
                turn = 0.0  # let the gait start before asking it to turn
            with quiet:
                policy.set_vel_cmd(speed, 0.0, turn)
            z = float(data.xpos[trunk][2])
            res["min_z"] = min(res["min_z"], z)
            if z > height + UPRIGHT:
                res["max_lat"] = max(res["max_lat"], abs(y))
                res["max_yaw"] = max(res["max_yaw"], abs(yaw))
                for side, s in foot_site.items():
                    res["max_foot_out"] = max(res["max_foot_out"], abs(float(data.site_xpos[s][1])))
                # The last state seen at walking height: what the steering
                # was looking at when things went wrong, if they do.
                res["upright_lat"], res["upright_yaw"], res["upright_t"] = y, yaw, t
            res["distance"] = x - x0
            res["walk_time"] = t - walk_t0

            if x >= finish_x:
                res["success"] = True
                phase = "done"
                stop_at = t + 0.5
                with quiet:
                    policy.set_vel_cmd(0.0, 0.0, 0.0)
                say(f"t={t:4.1f}s  crossed the finish line: {res['distance']:.2f} m in "
                    f"{res['walk_time']:.1f} s, y={y * 1000:+.1f} mm")

            if t - last_log >= log_every - 1e-9:
                last_log = t
                say(f"t={t:4.1f}s  x={x:+.2f}  y={y * 1000:+5.1f} mm  yaw={np.degrees(yaw):+5.1f} deg  "
                    f"turn cmd={turn:+.2f}  z={z:.3f}  feet y=({data.site_xpos[foot_site['left']][1] * 1000:+.0f}, "
                    f"{data.site_xpos[foot_site['right']][1] * 1000:+.0f}) mm  "
                    f"feet z=({data.site_xpos[foot_site['left']][2] * 1000:.0f}, "
                    f"{data.site_xpos[foot_site['right']][2] * 1000:.0f}) mm")

        policy.apply_action(policy.infer())
        for _ in range(DECIMATION):
            mujoco.mj_step(model, data)

        for _, rec in recs:
            rec.maybe_capture(i, data)

        # Step-off / fall detection, on the state after this tick.
        if phase in ("settle", "walk"):
            fail = None
            for c in range(data.ncon):
                con = data.contact[c]
                g1, g2 = con.geom1, con.geom2
                if floor in (g1, g2):
                    other = g2 if g1 == floor else g1
                    if other in feet:
                        foot = feet[other]
                        fy = float(data.site_xpos[foot_site[foot]][1])
                        fail = (f"{foot.upper()} foot touched the floor on the "
                                f"{'LEFT' if fy > 0 else 'RIGHT'} side of the beam "
                                f"(foot centre y={fy * 1000:+.0f} mm, edge at {np.sign(fy) * width * 500:+.0f} mm)")
                        res["fail_foot"], res["fail_side"], res["fail_foot_y"] = foot, "left" if fy > 0 else "right", fy
                    else:
                        oname = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, other)
                        fail = f"body geom '{oname}' touched the floor"
                    break
                if g1 in surfaces or g2 in surfaces:
                    other = g2 if g1 in surfaces else g1
                    if other not in feet:
                        oname = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, other)
                        fail = f"body geom '{oname}' touched the beam"
                        break
            z = float(data.xpos[trunk][2])
            if fail is None and z < height + FALL_HEIGHT:
                fail = f"trunk dropped to {z:.3f} m ({(z - height) * 1000:.0f} mm above the beam top)"
            if fail is not None:
                x, y = float(data.qpos[adr]), float(data.qpos[adr + 1])
                yaw = duck_sim.trunk_yaw(data, adr)
                res["fail"] = fail
                res["fail_t"] = t
                res["fail_lat"], res["fail_yaw"] = y, yaw
                if phase == "walk":
                    res["distance"] = x - x0
                    res["walk_time"] = t - walk_t0
                phase = "done"
                stop_at = t + AFTER_FAIL_S
                say(f"t={t:4.1f}s  STEPPED OFF after {res['distance']:.2f} m: {fail}; "
                    f"trunk y={y * 1000:+.1f} mm, heading {np.degrees(yaw):+.1f} deg, turn cmd {turn:+.2f}")

        if stop_at is not None and t >= stop_at:
            break

    say("")
    say(f"result:  {'SUCCESS' if res['success'] else 'FAILED'}  width {width * 1000:.0f} mm")
    say(f"  distance walked:   {res['distance']:.2f} m of {finish_x:.2f} m to the finish line")
    if res["fail_t"] is not None:
        say(f"  stepped off at:    t={res['fail_t']:.1f} s ({res['walk_time']:.1f} s of walking)")
        say(f"  how:               {res['fail']}")
        say(f"  at that moment:    trunk lateral error {res['fail_lat'] * 1000:+.1f} mm, heading {np.degrees(res['fail_yaw']):+.1f} deg")
        if res["upright_t"] is not None:
            say(f"  last upright:      t={res['upright_t']:.2f} s, lateral error {res['upright_lat'] * 1000:+.1f} mm, "
                f"heading {np.degrees(res['upright_yaw']):+.1f} deg")
    else:
        say(f"  walked for:        {res['walk_time']:.1f} s, no step-off")
    say(f"  max lateral error: {res['max_lat'] * 1000:.1f} mm (trunk vs centreline, while upright), "
        f"max heading {np.degrees(res['max_yaw']):.1f} deg, feet out to {res['max_foot_out'] * 1000:.0f} mm "
        f"(edge {width * 500:.0f} mm), lowest trunk {(res['min_z'] - height) * 1000:.0f} mm above the beam")
    for path, rec in recs:
        n = rec.write(path)
        say(f"  video:             {path} ({n} frames)")
    return res


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--width", type=float, default=0.10, help="beam width in m")
    p.add_argument("--length", type=float, default=2.0, help="beam length in m")
    p.add_argument("--height", type=float, default=0.04, help="beam height in m")
    p.add_argument("--speed", type=float, default=0.3, help="forward command (the policy walks ~0.13 m/s at 0.3)")
    p.add_argument("--seconds", type=float, default=25.0, help="time limit in sim seconds")
    p.add_argument("--y0", type=float, nargs="+", default=[0.0],
                   help="start the trunk this far off the centreline (m). A sweep runs every value "
                        "given, as separate trials, for each width; a single run uses the first")
    p.add_argument("--walking", default=WALKING_ONNX, help="walking policy ONNX")
    p.add_argument("--k-lat", type=float, default=8.0, help="rad of aim per m of lateral error")
    p.add_argument("--k-yaw", type=float, default=4.0, help="rad/s of yaw command per rad of heading error")
    p.add_argument("--max-aim", type=float, default=0.15, help="largest aim-off heading, rad")
    p.add_argument("--max-turn", type=float, default=1.0, help="largest yaw-rate command, rad/s")
    p.add_argument("--turn-bias", type=float, default=0.0,
                   help="constant added to the yaw command; the policy veers right by ~0.04 rad/s on its own")
    p.add_argument("--steer-delay", type=float, default=0.0,
                   help="send zero yaw command for this long after the walk starts (s)")
    p.add_argument("--runway", type=float, default=0.0,
                   help="length (m) of a 0.30 m wide start platform before the narrow beam; 0 = none")
    p.add_argument("--log-every", type=float, default=2.0, help="print a status line this often (sim s)")
    p.add_argument("--sweep", type=float, nargs="+", default=None,
                   help="run these widths in turn and print a table instead of one run")
    p.add_argument("--video", default=None, help="write an mp4 here (needs MUJOCO_GL=egl and a GPU)")
    p.add_argument("--fps", type=int, default=30)
    p.add_argument("--cam-distance", type=float, default=0.9)
    p.add_argument("--azimuth", type=float, nargs="+", default=[130.0],
                   help="camera azimuth(s); 90 = side view from the right, 180 = front view. "
                        "More than one writes one file per view with an _az<N> suffix")
    args = p.parse_args()

    common = dict(length=args.length, height=args.height, speed=args.speed, seconds=args.seconds,
                  k_lat=args.k_lat, k_yaw=args.k_yaw, max_aim=args.max_aim, max_turn=args.max_turn,
                  turn_bias=args.turn_bias, steer_delay=args.steer_delay, runway=args.runway,
                  walking=args.walking, log_every=args.log_every)

    if args.sweep is None:
        run(args.width, y0=args.y0[0], video=args.video, fps=args.fps, cam_distance=args.cam_distance,
            azimuths=tuple(args.azimuth), **common)
        return

    # The sim is deterministic, so one run per width is one sample. The start
    # offsets are the perturbation set: each width is tried from every y0.
    rows = []
    for w in args.sweep:
        trials = []
        for y0 in args.y0:
            r = run(w, y0=y0, verbose=False, **common)
            trials.append(r)
            print(f"width {w * 1000:5.0f} mm  y0 {y0 * 1000:+4.0f} mm: {'SUCCESS' if r['success'] else 'stepped off'}  "
                  f"{r['distance']:.2f} m  t={'-' if r['fail_t'] is None else '%.1f s' % r['fail_t']}  "
                  f"max lat {r['max_lat'] * 1000:.0f} mm"
                  + ("" if r["fail"] is None else f"  ({r['fail']})"), flush=True)
        rows.append((w, trials))

    finish_x = args.length - BEAM_BEHIND - FINISH_MARGIN
    print()
    print(f"beam {args.length:.1f} m x {args.height * 1000:.0f} mm high, speed {args.speed}, "
          f"finish at {finish_x:.2f} m, stance {rows[0][1][0]['stance'] * 1000:.1f} mm, "
          f"k_lat {args.k_lat} k_yaw {args.k_yaw} max_aim {args.max_aim} max_turn {args.max_turn} "
          f"turn_bias {args.turn_bias} steer_delay {args.steer_delay} runway {args.runway}, "
          f"start offsets {[round(v * 1000) for v in args.y0]} mm")
    print("| width (mm) | overhang (mm) | passed | distance min / mean (m) | stepped off at (s) | max lateral err (mm) | how it failed |")
    print("|---|---|---|---|---|---|---|")
    for w, trials in rows:
        n_ok = sum(r["success"] for r in trials)
        d = [r["distance"] for r in trials]
        offs = [r["fail_t"] for r in trials if r["fail_t"] is not None]
        off = "-" if not offs else ", ".join(f"{v:.1f}" for v in offs)
        hows = {}
        for r in trials:
            if r["fail"] is None:
                continue
            key = f"{r['fail_foot']} foot over the {r['fail_side']} edge" if "fail_foot" in r else "fell"
            hows[key] = hows.get(key, 0) + 1
        how = "-" if not hows else "; ".join(f"{k} x{v}" for k, v in hows.items())
        print(f"| {w * 1000:.0f} | {trials[0]['overhang'] * 1000:.1f} | {n_ok}/{len(trials)} | "
              f"{min(d):.2f} / {np.mean(d):.2f} | {off} | {max(r['max_lat'] for r in trials) * 1000:.0f} | {how} |")
    ok_all = [w for w, trials in rows if all(r["success"] for r in trials)]
    ok_any = [w for w, trials in rows if any(r["success"] for r in trials)]
    print()
    print("narrowest width that passed every start offset: "
          + (f"{min(ok_all) * 1000:.0f} mm" if ok_all else "none"))
    print("narrowest width that passed at least once:     "
          + (f"{min(ok_any) * 1000:.0f} mm" if ok_any else "none"))


if __name__ == "__main__":
    main()
